### ISSUE TITLE
Render blogs from /blogs collection

### ISSUE THREAD

**Issue by iamareebjamal** [amu-oss/amu2ias-frontend#16]
- [x] Populate collection with dummy data
- [x] Add blogs module in Vuex Store
- [x] Add blogs component 
- [x] Load blogs and render

**Comment by mohdomama** [comment]
@iamareebjamal are you working on this ?

**Comment by iamareebjamal** [comment]
No, I'll be working on user info

**Comment by mohdomama** [comment]
Okay i have two states in store/blogs:
`blogs` and `blogsRef`
where blogsRef = firestore.collection('blogs')
How do I set  blogs ? I was thinking to use blogsRef.get() but you have used `bindFirebaseRef` for something similar in auth module ?

**Comment by iamareebjamal** [comment]
Yes we are using vuexfire to bind data, look at this https://github.com/open-roboclub/roboclub-vue/blob/master/src/store/modules/news.js

**Comment by iamareebjamal** [comment]
Also, it'd be better to push a branch and open a WIP PR, so we can look at the code and collaborate
