### ISSUE TITLE
Implement About section

### ISSUE THREAD

**Issue by iamareebjamal** [amu-oss/amu2ias-frontend#21]
- [x] Use global collection to add about document
- [x] Populate necessary fields in about document
- [x] Discuss and design page layout
- [x] Bind firebase document to page

**Comment by mohdomama** [comment]
Apart from content and title, we would need links to the facebook page, twitter handle etc. of the amu2ias club. I think these links will also be added in `global > about` ? And should we mention developers also? In that case, their image url, github/gmail link should also be included in `global > about`.

**Comment by iamareebjamal** [comment]
Yes, we should use same document for all about use cases
