### ISSUE TITLE
Add Hall of Fame section

### ISSUE THREAD

**Issue by mohdomama** [amu-oss/amu2ias-frontend#27]
- [x] Discuss content that is to be displayed here
- [ ] Discuss and create layout
- [ ] Create `Hall of Fame` collection in firestore
- [ ] Create `fame` module in store. Fetch data from firebase

**Comment by mohdomama** [comment]
I think we will need a card for each `Hall of Fame` guy with the following data:
- AIR
- Year
- Category (IAS/IPS/IES)
- Image
- Email/Facebook/Google+ links

**Comment by mohdomama** [comment]
The admins/editors will have the option to delete entries. Also should we provide an option to store images directly in firebase or ask for an image link instead?

**Comment by iamareebjamal** [comment]
To store, because the same will have to be done for blogs
