### ISSUE TITLE
Do we put .lock file under version control?

### ISSUE THREAD

**Issue by RJ722** [amu-oss/amu2ias-frontend#53]
Is it a good idea to keep the `.lock` file under version control? Also, we are getting a conflict in #52

**Comment by iamareebjamal** [comment]
Yes we do

**Comment by mohdomama** [comment]
@RJ722 
> The package.json describes the intended versions desired by the original author, while yarn.lock describes the last-known-good configuration for a given application.

https://github.com/yarnpkg/yarn/issues/838#issuecomment-253362537
