### ISSUE TITLE
Add auth

### ISSUE THREAD

**Issue by mohdomama** [amu-oss/amu2ias-frontend#9]
As of now, I have enabled authentication with : google, facebook, twitter, github and email in firebase.
We have to add the same in the web app.

**Comment by mohdomama** [comment]
As far as I know, there are two kinds of roles : normal, editor.
Once the user has signed in, the editors/owners of the firebase account will manually add him as an editor if required.
Thats how we will proceed right ? @iamareebjamal

**Comment by iamareebjamal** [comment]
We will later provide another interface to allow owners to change roles of registered users

**Comment by iamareebjamal** [comment]
@mohdomama Create one more firebase app for production `amu2ias`

Without `-firebase`

**Comment by mohdomama** [comment]
@iamareebjamal Then I will have to create more production apps for facebook, twitter and github as well.
PS the fire base name of the app requires a special character I think. It was not allowing `amu2ias`

**Comment by mohdomama** [comment]
Why do we need a different app for production ?

**Comment by iamareebjamal** [comment]
We will test data and add dummy auths in dev app. We will also have less strict security rules in dev app. We can't let production data get deleted or compromised. Don't worry, we will use same OAuth app for both accounts. That is no issue

**Comment by iamareebjamal** [comment]
Try `amu-ias`

**Comment by mohdomama** [comment]
Done

**Comment by mohdomama** [comment]
Areeb bhai .. where is the master being deployed ?

**Comment by iamareebjamal** [comment]
amu2ias.surge.sh
